service:
  name: microservice-starter

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  init:
    handler: dist/app.init
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
