service:
  name: microservice-starter

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  init:
    handler: dist/app.init
    package:
      exclude:
        - dist/**
        - src/**
      include:
        - src/app.js
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


