service:
  name: microservice-starter

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          method: get
          path: hello
